name: test

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: stoys_2.12
            java_version: 8
            maven_extra_args: -Pjava-8,scala-2.12,spark-3.0
            experimental: false
          - name: stoys_2.13
            java_version: 11
            maven_extra_args: -Pjava-11,scala-2.13,spark-3.2
            experimental: false
          - name: upstream
            java_version: 17
            maven_extra_args: -Pjava-17,scala-2.13,spark-3.3
            experimental: true

    continue-on-error: ${{ matrix.experimental }}

    name: ${{ matrix.name }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: ${{ matrix.java_version }}
          cache: maven

      - name: Build with Maven
        run: mvn --batch-mode verify ${{ matrix.maven_extra_args }}
