name: test

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: default
            java_version: 8
            maven_extra_args: -Pjava-8,scala-2.12,spark-3.0
            experimental: false
          - name: legacy
            java_version: 8
            maven_extra_args: -Pjava-8,scala-2.11,spark-2.4
            experimental: false
          - name: future
            java_version: 15
            maven_extra_args: -Pjava-15,scala-2.13,spark-3.2
            experimental: true

    continue-on-error: ${{ matrix.experimental }}

    name: ${{ matrix.name }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: ${{ matrix.java_version }}
          cache: maven

      - name: Build with Maven
        run: mvn --batch-mode verify ${{ matrix.maven_extra_args }}
