name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test__default:
    runs-on: ubuntu-latest

    name: default

    steps:
      - uses: actions/checkout@v2

      - name: Cache ~/.m2/repository
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-default-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-default-maven-

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: mvn clean verify
        run: mvn -B clean verify

  test__legacy:
    runs-on: ubuntu-latest

    name: legacy

    steps:
      - uses: actions/checkout@v2

      - name: Cache ~/.m2/repository
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-legacy-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-legacy-maven-

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: mvn clean verify
        run: |
          mvn scala-cross-build:change-version -Pscala-2.11
          mvn -B clean verify -Pjava-8,scala-2.11,spark-2.4

  test__cutting_edge:
    runs-on: ubuntu-latest

    name: cutting_edge

    steps:
      - uses: actions/checkout@v2

      - name: Cache ~/.m2/repository
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-cutting_edge-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-cutting_edge-maven-

      - name: Set up Java
        uses: actions/setup-java@v1
        with:
          java-version: 15

      - name: mvn clean verify
        run: |
          mvn scala-cross-build:change-version -Pscala-2.13
          mvn -B clean verify -Pjava-15,scala-2.13,spark-3.2
